Add a pair-by-pair SOAP spherical expansion calculator
Luthaf/rascaline pull request #147
Opened 2023-01-05 14:47 UTC by Luthaf

This is only the first step, but I'm opening this since I've already re-written this code 3 times, so let's try to merge it before I have to rewrite it a fourth time!

This is currently in a state where the base code is shared between pair-by-pair calculation and full spx calculation, and the pair-by-pair code can compute the values (no gradients) of the spherical expansion.

Still TBD:
- [ ] add support for gradients
- [ ] add parallelism over pairs (this might be a separate PR)
- [ ] use pair-by-pair calculator as an alternative implementation of the full spx when only having a handful of systems (this should bring better parallelism that trying to parallelize over systems) (this might be a separate PR)
- [ ] Add tests
- [ ] Fix all remaining TODO

2023-01-09 14:40 UTC, Luthaf commented
(first three commits are from #148, you can ignore them!)

2023-01-09 16:10 UTC, agoscinski requested changes
Summary to verify if I understood correctly the PR: SphericalExpansion logic has been slimmed-down by moving the computation of pair contributions from `SphericalExpansion.compute_for_pair` to a new struct `SphericalExpansionByPair.compute_for_pair`. Similarly, the `samples` function from `FullNeighborList`, has been splitted into `samples` and `samples_for`. It is just a shifting of logic, no new feature has been implemented. I guess it is important for some later feature, so the pair contribution calculator can be reused for the n-centers descriptor?

Seems alright to me. Only the documentation of `SphericalExpansionByPair` is not so understandable IMO. I proposed something in the review which is hopefully not too heavy in math. Fee free to change it, but a bit more doc is needed.

Side note (not really important, not worth the effort to change it, but I just need to mention it): I don't like that the name "factor" for constant prefactors. I feel like "prefactor", "global_factor" or "constant_factor" are clearer names.

2023-01-10 11:34 UTC, Luthaf commented on python/rascaline/calculators.py
> +class SphericalExpansionByPair(CalculatorBase):
I've updated this part of the documentation, let me know if it is clearer!

2023-01-10 11:35 UTC, Luthaf commented
> SphericalExpansion logic has been slimmed-down by moving the computation of pair contributions from SphericalExpansion.compute_for_pair to a new struct SphericalExpansionByPair.compute_for_pair. Similarly, the samples function from FullNeighborList, has been splitted into samples and samples_for. It is just a shifting of logic, no new feature has been implemented. I guess it is important for some later feature, so the pair contribution calculator can be reused for the n-centers descriptor?

This is a very accurate understanding! The new SphericalExpansionByPair calculator is sharing code with FullNeighborList for sample generation (i.e. finding all pairs in a system), and other code with spherical expansion (to compute individual pair contributions)

2023-01-10 12:55 UTC, agoscinski approved these changes
Looks good now! Happy new merge!

2023-01-10 12:59 UTC, merged